name: Development build

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build

    steps:
      - name: Clone project
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Package (don't release)
        uses: BigWigsMods/packager@master
        with:
          args: -l -d -z # Skip localization, upload, and zip creation
