name: Pull request check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone project
        uses: actions/checkout@v7

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning
